name: n8n-job-scout
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-job-scout
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Chicago
      - TZ=America/Chicago
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/workflows

volumes:
  n8n_data:
